import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import { Box, Button, Card, CardContent, CardMedia, Icon, Stack, Typography, Link} from '@mui/material'
import Timer from '@/component2/timer'; 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const weddingsDay = new Date("2023-10-07").getTime();
  const dateTimeAfterWedding = weddingsDay;

  return (
    <>
      <Head>
        <title>Invitación - Carolina & Leandro</title>
        <meta name="description" content="Generated by Johanna Chamorro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card sx={{
          width:'100%', 
          height:{
            xs:'100vh', 
            md:'100vh'
          }, 
          p:0, 
          backgroundColor:'#8D9F6F', 
          boxShadow:'none', 
          position:'relative'
          }}>
          <CardMedia
              component="img"
              image="/a.png"
              alt="flower background"
              sx={{display:{xs:'none', md:'block'}, width:'100vw'}}
            >
          </CardMedia>
          <CardMedia
              component="img"
              image="/mobile.png"
              alt="flower background"
              sx={{display:{md:'none'}}}
            >
          </CardMedia>
          <Box sx={{
            position:'absolute', 
            backgroundColor:'#ffff', 
            p:2,
            bottom:0, 
            left:0, 
            right:0, 
            marginLeft:'auto', 
            marginRight:'auto', 
            width:{xs:'95%', md:'70%'},
            height:{xs:'95%'},
            borderRadius:'2px',
            }}>
            <Card sx={{
              width:{xs:'100%', md:'95%'}, 
              boxShadow:'none', 
              border:'none', 
              borderRadius:0, 
              margin:'auto'
              }}>
              <CardContent sx={{p:{xs:0, md:2}, display:'flex', flexDirection:'column', justifyContent:'center'}}>
                <Typography gutterBottom component="div" sx={{textAlign:'center', fontSize:{xs:20, md:60}, display:{xs:'none', md:'block'}}}>
                  Carolina & Leandro
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{textAlign:'center', display:{xs:'none', md:'block'}}}>
                Después de muchas aventuras compartidas, el 7 de Octubre del 2023 daremos el “sí quiero”, continuaremos este emocionante viaje juntos y nos encantaría que nos acompañes a celebrar la fiesta de nuestra boda, llena de brindis, risas y bailes hasta el amanecer.
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{textAlign:'center', display:{xs:'none', md:'block'}, pt:3}}>
                ¡Prepárense para una noche inolvidable!
                </Typography>
              </CardContent>
              <CardMedia
                sx={{ height:{xs:300 , md:500, lg:600}}}
                image="/WhatsApp Image 2023-06-12 at 21.18.58.jpeg"
                title="couple photo"
              />
              <CardContent sx={{display:'flex', flexDirection:'column', justifyContent:'center', width:'100%'}}>
                <Typography gutterBottom component="div" sx={{textAlign:'center', fontSize:{xs:30, md:60}, display:{xs:'block', md:'none'}, pt:2}}>
                  Carolina & Leandro
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{textAlign:'center', display:{xs:'block', md:'none'}, pt:3}}>
                Después de muchas aventuras compartidas, el 7 de Octubre del 2023 daremos el “sí quiero”, continuaremos este emocionante viaje juntos y nos encantaría que nos acompañes a celebrar la fiesta de nuestra boda, llena de brindis, risas y bailes hasta el amanecer.
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{textAlign:'center', display:{xs:'block', md:'none'}, pt:3}}>
                ¡Prepárense para una noche inolvidable!
                </Typography>
                <KeyboardArrowDownIcon sx={{margin:'auto', color:'#55783B', mt:0.5}}/>
              </CardContent>
            </Card>
          </Box>
        </Card>
        <Card sx={{backgroundColor:'#FDF0DF', height:'auto', width:'100%', position:'relative',  display:'flex', flexDirection:{xs:'column', md:'row'}, padding:{xs:5, md:10}, justifyContent:'center', gap:{xs:5, md:35},  borderRadius:0}}>
            <Card sx={{backgroundColor:'transparent', border:'none', boxShadow:'none', display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
              <img src={"/rings.svg"} height={88} width={98}/>
              <Typography sx={{mt:3, mb:1}}>Parroquia Nuestra Señora de Fátima</Typography>
              <Typography>80 Av. Fernando Elías</Typography>
              <Typography>7 de Octubre a las 20:30 hs.</Typography>
              <Button href='https://goo.gl/maps/jtvSVY3skCSYGNY29' variant="contained" sx={{textTransform:'uppercase', backgroundColor:'#55783B', mt:2, fontSize:12}}>ver mapa</Button>
            </Card>
            <Card sx={{backgroundColor:'transparent', border:'none', boxShadow:'none', display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
              <img src={"/glass.svg"} height={89} width={94} />
              <Typography sx={{mt:3, mb:1}}>Salón Circulo de Oficiales de la Policía</Typography>
              <Typography>3304, Garupa, Misiones</Typography>
              <Typography>7 de Octubre a las 21:15 hs.</Typography>
              <Button href='https://goo.gl/maps/7hrzJsjFLR8szCrA7' variant="contained" sx={{textTransform:'uppercase', backgroundColor:'#55783B', mt:2, fontSize:12}}>ver mapa</Button>
            </Card>
        </Card>
        <Card sx={{backgroundColor:'#FFFF', height:'auto', width:'100%', position:'relative',  display:'flex', flexDirection:{xs:'column', md:'row'}, padding:{xs:5, md:10}, justifyContent:'center', gap:{xs:5, md:35}, borderRadius:0}}>
            <Card sx={{backgroundColor:'transparent', border:'none', boxShadow:'none', display:'flex', flexDirection:'column', alignItems:'center', gap:{xs:2, md:5}}}>
              <Typography sx={{mt:3, mb:1, fontSize:{xs:20, md:30}, textAlign:'center'}}>CONFIRMACIÓN DE ASISTENCIA</Typography>
              <Box sx={{display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
                <Typography>No será lo mismo sin vos. </Typography>
                <Typography>Por favor confirmar asistencia antes del 24 de septiembre de 2023.</Typography>
              </Box>
              <Box sx={{display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
              </Box>
              <Button href='https://forms.gle/yebAkmjcXg7JHN9d6' variant="contained" sx={{textTransform:'uppercase', backgroundColor:'#55783B', mt:2, fontSize:12}}>Confirmar asistencia</Button>
            </Card>
        </Card>
        <Card sx={{backgroundColor:'#FDF0DF', height:'auto', width:'100%', position:'relative',  display:'flex', flexDirection:{xs:'column', md:'row'}, padding:{xs:5, md:10}, justifyContent:'center', gap:{xs:5, md:35}, borderRadius:0}}>
            <Card sx={{backgroundColor:'transparent', border:'none', boxShadow:'none', display:'flex', flexDirection:'column', alignItems:'center', gap:{xs:1, md:3}}}>
              <Typography sx={{ mb:1, fontSize:{xs:20, md:30}, textAlign:'center'}}>FALTAN</Typography>
                <Timer />
              <Box sx={{display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
                <Typography>No será lo mismo sin vos. </Typography>
                <Typography>Por favor confirmar asistencia antes del 24 de septiembre de 2023.</Typography>
              </Box>
            </Card>
        </Card>
        <Card sx={{backgroundColor:'#FFFF', height:'auto', width:'100%', position:'relative',  display:'flex', flexDirection:{xs:'column', md:'row'}, padding:{xs:5, md:10}, justifyContent:'center', gap:{xs:5, md:35}, borderRadius:0}}>
            <Card sx={{backgroundColor:'transparent', border:'none', boxShadow:'none', display:'flex', flexDirection:'column', alignItems:'center', gap:{xs:1, md:3}}}>
              <Typography sx={{mt:3, mb:1, fontSize:{xs:20, md:25}, textAlign:'center'}}>Contacto</Typography>
              <Box sx={{display:'flex', flexDirection:'column', alignItems:'center', textAlign:'center'}}>
                <Typography>Comunicate via whatsapp</Typography>
                <Button href='https://api.whatsapp.com/send?phone=5493764615506' variant="contained" sx={{textTransform:'uppercase', backgroundColor:'#55783B', mt:2, fontSize:12}}>Contacto</Button>
              </Box>
            </Card>
        </Card>
      </main>
    </>
  )
}
